import React from 'react'
import image1 from "../assets/images/sf/sf (1).png"
import image2 from "../assets/images/sf/sf (2).png"
import image3 from "../assets/images/sf/sf (3).png"
import image4 from "../assets/images/sf/sf (4).png"
import image5 from "../assets/images/sf/sf (5).png"
import image6 from "../assets/images/sf/sf (6).png"
import image7 from "../assets/images/sf/sf (7).png"
import image8 from "../assets/images/sf/sf (8).png"
import Wrapper from '../layouts/Wrapper'


const SpacialFeatures = () => {
  return (
    <section className='py-16 md:pt-24'>
    <Wrapper>

        <div className='text-center pb-10'>
            
            <h1 className='text-3xl md:leading-[3.5rem] mb-1 font-semibold md:text-5xl '>
                How would Selling on Zeed
                <span className='text-colthree font-bold'> Benefit you </span> ? 
                </h1>
          
        </div>

        <div className='md:flex gap-6 justify-center align-middle'>   
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100  rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image1} alt="image1" />
                <h2 className='text-2xl my-2 font-semibold'>Focus on What Matters the Most</h2>
                <p>Let us handle the logistics and payment process, so you can focus on what you do best - selling your products and serving your customers without worrying about logistics complexities.</p>
            </div>
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100 rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image4} alt="image4" />
                <h2 className='text-2xl my-2 font-semibold'>Lightning-Fast Delivery</h2>
                <p>Our same-day delivery option ensures that your customers receive their orders quickly, giving you a competitive edge in providing exceptional service and customer satisfaction.</p>
            </div>
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100 rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image3} alt="image3" />
                <h2 className='text-2xl my-2 font-semibold'>Vendor Dashboard</h2>
                <p>Stay in control of your sales and orders with our user-friendly dashboard, providing you with valuable insights and tools to optimize your operations and boost your sales.</p> 
            </div>
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100 rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image2} alt="image2" />
                <h2 className='text-2xl my-2 font-semibold'>Quick Onboarding</h2>
                <p>With our seamless onboarding process, you can start selling within hours without any paperwork, allowing you to quickly capitalize on the market opportunities.</p> 
            </div>
            
        </div>

        <div className='md:flex gap-6 justify-center align-middle mt-6'>   
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100  rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image8} alt="image8" />
                <h2 className='text-2xl my-2 font-semibold'>Seamless Product Posting</h2>
                <p>Post your products instantly, just like posting on social media, and experience the ease of managing your inventory and sales with a user-friendly interface, saving you time and effort.</p>
            </div>
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100 rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image7} alt="image7" />
                <h2 className='text-2xl my-2 font-semibold'>Reach Your Target Audience Efficiently</h2>
                <p>Our personalized product recommendation feature helps you reach your target audience with precision, enabling you to effortlessly promote your products to potential customers who are interested in your specialties.</p>
            </div>
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100 rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image6} alt="image6" />
                <h2 className='text-2xl my-2 font-semibold'>Autogenerated Marketing</h2>
                <p>Amplify your sales through influencers, as their followers can easily purchase your products with a simple click, expanding your customer base and driving more sales without any additional costs.</p> 
            </div>
            <div className='md:w-1/4 mb-4 md:mb-0 p-10 h-auto border-2 border-slate-400 hover:border-slate-50 duration-100 rounded-xl'>
                <img className='rounded-xl mb-5 w-[150px] h-auto mx-auto' src={image5} alt="image5" />
                <h2 className='text-2xl my-2 font-semibold'>Our Success Depends on Your Success</h2>
                <p>Enjoy the flexibility of no minimum contract duration and no fixed monthly/annual fees. With our commission-based pricing, we give you the freedom to manage your business on your own terms, guaranteeing that if you do not profit from our partnership, you will not lose.</p> 
            </div>
            
        </div>
    </Wrapper>
</section>
  )
}

export default SpacialFeatures